Fix/dev help
ProgrammingPhilippines/progphil-bot pull request #244
Opened 2024-08-10 02:01 UTC by mystique09

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
This Pr includes:
- fix: dev-help solve button not responding due to logging error
- chore: add logger on other View to track errors

Fixes #243 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Manual Testing

**Test Configuration**:
* Firmware version: N/A
* Hardware: N/A
* Toolchain: N/A
* SDK: N/A

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-08-10 02:06 UTC, mystique09 commented
![image](https://github.com/user-attachments/assets/8cbf29e5-1331-4230-ae61-831e4a745966)

2024-08-15 09:24 UTC, mystique09 commented
![image](https://github.com/user-attachments/assets/93009195-9040-49ae-92ac-fdf9401ef433)

2024-08-15 15:13 UTC, kylecdrck requested changes

2024-08-15 15:13 UTC, kylecdrck commented on src/bot/main.py
> +    config = get_config("config/dev-config.yml")
You must have forgotten about this. We only use the *dev-* prefix on the repo side. The config is used in actual is just config

2024-08-16 17:29 UTC, kylecdrck approved these changes

2024-08-16 17:30 UTC, merged