Feat/#12 auto responder
ProgrammingPhilippines/progphil-bot pull request #77
Opened 2023-02-15 10:27 UTC by Jedddy

# Description

Added a database package, Added new feature: Auto responder

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Manually tested inside my own test server

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-15 12:55 UTC, vouchard approved these changes
Please indicate what ops need to deploy this successfully,
db schema, things that need to be added in config.yml etc

2023-02-16 09:12 UTC, ShindouMihou requested changes

2023-02-16 09:12 UTC, ShindouMihou commented on bot/cogs/auto_responder.py
> +             description="Gets all automated responses.")
Also please move this `/view responses` or `/responses view`.

2023-02-16 09:12 UTC, ShindouMihou commented on bot/cogs/auto_responder.py
> +    @command(name="addresponse",
Please move all related commands like `/addresponse` to `/responses add` to give us more room to add more commands in the future (since a single command can have an extra 50 subcommands and an extra 50 subcommands per subcommand group as well).

2023-02-16 09:12 UTC, ShindouMihou commented on bot/cogs/auto_responder.py
> +    @command(name="deleteresponse",
`/response delete`

2023-02-16 13:08 UTC, CunningBard requested changes

2023-02-16 13:08 UTC, CunningBard commented on bot/cogs/auto_responder.py
> +                condition = response["message"] in message.content
move this within
```
if len(response["message"].split()) > 1:
    ...
```
idk what the purpose of `is_phrase` is, please explain 😭

2023-02-16 13:08 UTC, CunningBard commented on bot/cogs/auto_responder.py
> +            for num, response in enumerate(data, start=1):
use `_format_description`?

2023-02-16 13:10 UTC, Jedddy commented on bot/cogs/auto_responder.py
> +                condition = response["message"] in message.content
is phrase just checks if the trigger message is a phrase, more than 1 word

2023-02-16 13:11 UTC, CunningBard commented on bot/cogs/auto_responder.py
> +                condition = response["message"] in message.content
but couldnt you move the
```
condition = response["message"] in message.content
```
into the if statement instead of adding an `is_phrase`?

2023-02-16 13:14 UTC, Jedddy commented on bot/cogs/auto_responder.py
> +                condition = response["message"] in message.content
we only want that condition if the trigger is a phrase, if not, we need to check if the single word trigger is their own word in the chat

2023-02-16 13:15 UTC, Jedddy commented on bot/cogs/auto_responder.py
> +            for num, response in enumerate(data, start=1):
circular imports, unless i move the function to its own file

2023-02-16 13:18 UTC, CunningBard commented on bot/cogs/auto_responder.py
> +                condition = response["message"] in message.content
`is_phrase = len(response["message"].split()) > 1` ???

2023-02-16 13:20 UTC, Jedddy commented on bot/cogs/auto_responder.py
> +                condition = response["message"] in message.content
ok that might work but WE are newbie friendly

2023-02-16 13:21 UTC, CunningBard commented on bot/cogs/auto_responder.py
> +                condition = response["message"] in message.content
okayy finee, I was just confused that you didnt use it, you can leave it be

2023-02-16 13:21 UTC, CunningBard approved these changes
LGTM

2023-02-16 13:21 UTC, Jedddy commented on bot/cogs/auto_responder.py
> +                condition = response["message"] in message.content
*ok soldiers stand down, tell the helicopters we didnt need the machine gun after all*

2023-02-17 04:41 UTC, vouchard approved these changes

2023-02-17 04:57 UTC, merged